# Mirror the mod plugin from the kit (the editor's source of truth) into the repo: zonekit\<Mod>\ and the
# classifier lists. Run after every editor save the tester reports, before any cook, and before committing.
# Usage:  powershell -File harness\tools\mirror_from_kit.ps1 [-Mod X] [-WhatIf]
# Copies .uplugin, Content\ and Resources\ only (never Intermediate\ / Saved\). Files deleted in the kit are deleted in
# the repo copy too (robocopy /MIR), so the repo matches what will cook.
param([string]$Mod, [switch]$WhatIf)
. "$PSScriptRoot\common.ps1"
Assert-Setup kit
$Mod = Get-ModName $Mod
$src = "$Kit\Stalker2\Mods\$Mod"
$dst = "$Repo\zonekit\$Mod"
if (-not (Test-Path "$src\$Mod.uplugin")) { throw "no plugin at $src" }
$flags = @("/NJH", "/NJS", "/NP", "/NDL")
if ($WhatIf) { $flags += "/L" }
New-Item -ItemType Directory -Force $dst | Out-Null
Copy-Item "$src\$Mod.uplugin" "$dst\$Mod.uplugin" -Force -WhatIf:$WhatIf
foreach ($d in "Content", "Resources") {
    if (Test-Path "$src\$d") { robocopy "$src\$d" "$dst\$d" /MIR @flags | Where-Object { $_.Trim() } }
}
$kitCls = "$Kit\Stalker2\SavedMods\PackageClassifier\$Mod"
if (Test-Path $kitCls) {
    New-Item -ItemType Directory -Force "$Repo\zonekit\tools\classifier\$Mod" | Out-Null
    Copy-Item "$kitCls\*.txt" "$Repo\zonekit\tools\classifier\$Mod" -Force -WhatIf:$WhatIf
}
# Editor droppings that must not ship unless an actor override needs them
Get-ChildItem "$src\Content" -Filter "Autogenerated_*_ActorReplacementData.uasset" -ErrorAction SilentlyContinue |
    ForEach-Object { Write-Host "NOTE: $($_.Name) is in the kit mod's Content; it gets cooked. Delete it unless an actor override needs it." }
exit 0
